[WIP] eu/migrate templates
utecuy/utec-theme pull request #1
Opened 2016-12-12 21:46 UTC by Bound3R

### Description
This PR in a migracion the theme of cypress to eucalyptus 

### Testing
- [x] templates
- [ ] extra templates
- [ ] assets

### Notes
I have not been able to test it on the platform with eucalyptus... :sweat: 

### Reviewers
@felipemontoya @jfavellar90 @diegomillan

2016-12-13 23:44 UTC, Bound3R commented
@felipemontoya :eyes:

2016-12-14 01:27 UTC, felipemontoya requested changes
Some minor changes and we are ready for this. For the sake of order we can also squash into meaningful commits

2016-12-14 01:27 UTC, felipemontoya commented on templates/index.html
> +% endif
end of line

2016-12-14 01:27 UTC, felipemontoya commented on templates/index.html
> +            ## Translators: 'Open edX' is a brand, please keep this untranslated. See http://openedx.org for more information.
we could remove this comment and the next since we als removed the open edx brand

2016-12-14 21:16 UTC, felipemontoya approved these changes

2016-12-14 21:16 UTC, merged